name: continuous integration
# yamllint disable-line rule:truthy
on:
- push
- pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test if sources exist to prevent non existent pushes
      run: |
        ./bootstrap.sh
